# Generated by Django 5.2.4 on 2025-08-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog_previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_publish', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['title'],
            },
        ),
    ]
