# Generated by Django 5.2.4 on 2025-09-04 16:29

import usersapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', usersapp.models.CustomUserManager()),
            ],
        ),
    ]
